import scrapy
from urllib.parse import urlencode
#from SampleData.items import names

API_KEY = '983e9cb8-ec3e-4d5f-9ae1-874837c26cbe'


def get_scrapeops_url(url):
    payload = {'api_key': API_KEY, 'url': url}
    proxy_url = 'https://proxy.scrapeops.io/v1/?' + urlencode(payload)
    return proxy_url


class QuotesSpider(scrapy.Spider):

    name = "urls_city"

    def start_requests(self):

        urls = [
                'https://www.rumah.com/agen-properti/dki-jakarta/2',
                'https://www.rumah.com/agen-properti/dki-jakarta/3',
                'https://www.rumah.com/agen-properti/dki-jakarta/4',
                'https://www.rumah.com/agen-properti/dki-jakarta/5',
                'https://www.rumah.com/agen-properti/dki-jakarta/6',
                'https://www.rumah.com/agen-properti/dki-jakarta/7',
                'https://www.rumah.com/agen-properti/dki-jakarta/8',
                'https://www.rumah.com/agen-properti/dki-jakarta/9',
                'https://www.rumah.com/agen-properti/dki-jakarta/10',
                'https://www.rumah.com/agen-properti/dki-jakarta/11',
                'https://www.rumah.com/agen-properti/dki-jakarta/12',
                'https://www.rumah.com/agen-properti/dki-jakarta/13',
                'https://www.rumah.com/agen-properti/dki-jakarta/14',
                'https://www.rumah.com/agen-properti/dki-jakarta/15',
                'https://www.rumah.com/agen-properti/dki-jakarta/16',
                'https://www.rumah.com/agen-properti/dki-jakarta/17',
                'https://www.rumah.com/agen-properti/dki-jakarta/18',
                'https://www.rumah.com/agen-properti/dki-jakarta/19',
                'https://www.rumah.com/agen-properti/dki-jakarta/20',
                'https://www.rumah.com/agen-properti/dki-jakarta/21',
                'https://www.rumah.com/agen-properti/dki-jakarta/22',
                'https://www.rumah.com/agen-properti/dki-jakarta/23',
                'https://www.rumah.com/agen-properti/dki-jakarta/24',
                'https://www.rumah.com/agen-properti/dki-jakarta/25',
                'https://www.rumah.com/agen-properti/dki-jakarta/26',
                'https://www.rumah.com/agen-properti/dki-jakarta/27',
                'https://www.rumah.com/agen-properti/dki-jakarta/28',
                'https://www.rumah.com/agen-properti/dki-jakarta/29',
                'https://www.rumah.com/agen-properti/dki-jakarta/30',
                'https://www.rumah.com/agen-properti/dki-jakarta/31',
                'https://www.rumah.com/agen-properti/dki-jakarta/32',
                'https://www.rumah.com/agen-properti/dki-jakarta/33',
                'https://www.rumah.com/agen-properti/dki-jakarta/34',
                'https://www.rumah.com/agen-properti/dki-jakarta/35',
                'https://www.rumah.com/agen-properti/dki-jakarta/36',
                'https://www.rumah.com/agen-properti/dki-jakarta/37',
                'https://www.rumah.com/agen-properti/dki-jakarta/38',
                'https://www.rumah.com/agen-properti/dki-jakarta/39',
                'https://www.rumah.com/agen-properti/dki-jakarta/40',
                'https://www.rumah.com/agen-properti/dki-jakarta/41',
                'https://www.rumah.com/agen-properti/dki-jakarta/42',
                'https://www.rumah.com/agen-properti/dki-jakarta/43',
                'https://www.rumah.com/agen-properti/dki-jakarta/44',
                'https://www.rumah.com/agen-properti/dki-jakarta/45',
                'https://www.rumah.com/agen-properti/dki-jakarta/46',
                'https://www.rumah.com/agen-properti/dki-jakarta/47',
                'https://www.rumah.com/agen-properti/dki-jakarta/48',
                'https://www.rumah.com/agen-properti/dki-jakarta/49',
                'https://www.rumah.com/agen-properti/dki-jakarta/50',
                'https://www.rumah.com/agen-properti/dki-jakarta/51',
                'https://www.rumah.com/agen-properti/dki-jakarta/52',
                'https://www.rumah.com/agen-properti/dki-jakarta/53',
                'https://www.rumah.com/agen-properti/dki-jakarta/54',
                'https://www.rumah.com/agen-properti/dki-jakarta/55',
                'https://www.rumah.com/agen-properti/dki-jakarta/56',
                'https://www.rumah.com/agen-properti/dki-jakarta/57',
                'https://www.rumah.com/agen-properti/dki-jakarta/58',
                'https://www.rumah.com/agen-properti/dki-jakarta/59',
                'https://www.rumah.com/agen-properti/dki-jakarta/60',
                'https://www.rumah.com/agen-properti/dki-jakarta/61',
                'https://www.rumah.com/agen-properti/dki-jakarta/62',
                'https://www.rumah.com/agen-properti/dki-jakarta/63',
                'https://www.rumah.com/agen-properti/dki-jakarta/64',
                'https://www.rumah.com/agen-properti/dki-jakarta/65',
                'https://www.rumah.com/agen-properti/dki-jakarta/66',
                'https://www.rumah.com/agen-properti/dki-jakarta/67',
                'https://www.rumah.com/agen-properti/dki-jakarta/68',
                'https://www.rumah.com/agen-properti/dki-jakarta/69',
                'https://www.rumah.com/agen-properti/dki-jakarta/70',
                'https://www.rumah.com/agen-properti/dki-jakarta/71',
                'https://www.rumah.com/agen-properti/dki-jakarta/72',
                'https://www.rumah.com/agen-properti/dki-jakarta/73',
                'https://www.rumah.com/agen-properti/dki-jakarta/74',
                'https://www.rumah.com/agen-properti/dki-jakarta/75',
                'https://www.rumah.com/agen-properti/dki-jakarta/76',
                'https://www.rumah.com/agen-properti/dki-jakarta/77',
                'https://www.rumah.com/agen-properti/dki-jakarta/78',
                'https://www.rumah.com/agen-properti/dki-jakarta/79',
                'https://www.rumah.com/agen-properti/dki-jakarta/80',
                'https://www.rumah.com/agen-properti/dki-jakarta/81',
                'https://www.rumah.com/agen-properti/dki-jakarta/82',
                'https://www.rumah.com/agen-properti/dki-jakarta/83',
                'https://www.rumah.com/agen-properti/dki-jakarta/84',
                'https://www.rumah.com/agen-properti/dki-jakarta/85',
                'https://www.rumah.com/agen-properti/dki-jakarta/86',
                'https://www.rumah.com/agen-properti/dki-jakarta/87',
                'https://www.rumah.com/agen-properti/dki-jakarta/88',
                'https://www.rumah.com/agen-properti/dki-jakarta/89',
                'https://www.rumah.com/agen-properti/dki-jakarta/90',
                'https://www.rumah.com/agen-properti/dki-jakarta/91',
                'https://www.rumah.com/agen-properti/dki-jakarta/92',
                'https://www.rumah.com/agen-properti/dki-jakarta/93',
                'https://www.rumah.com/agen-properti/dki-jakarta/94',
                'https://www.rumah.com/agen-properti/dki-jakarta/95',
                'https://www.rumah.com/agen-properti/dki-jakarta/96',
                'https://www.rumah.com/agen-properti/dki-jakarta/97',
                'https://www.rumah.com/agen-properti/dki-jakarta/98',
                'https://www.rumah.com/agen-properti/dki-jakarta/99',
                'https://www.rumah.com/agen-properti/dki-jakarta/100',
                'https://www.rumah.com/agen-properti/dki-jakarta/101',
                'https://www.rumah.com/agen-properti/dki-jakarta/102',
                'https://www.rumah.com/agen-properti/dki-jakarta/103',
                'https://www.rumah.com/agen-properti/dki-jakarta/104',
                'https://www.rumah.com/agen-properti/dki-jakarta/105',
                'https://www.rumah.com/agen-properti/dki-jakarta/106',
                'https://www.rumah.com/agen-properti/dki-jakarta/107',
                'https://www.rumah.com/agen-properti/dki-jakarta/108',
                'https://www.rumah.com/agen-properti/dki-jakarta/109',
                'https://www.rumah.com/agen-properti/dki-jakarta/110',
                'https://www.rumah.com/agen-properti/dki-jakarta/111',
                'https://www.rumah.com/agen-properti/dki-jakarta/112',
                'https://www.rumah.com/agen-properti/dki-jakarta/113',
                'https://www.rumah.com/agen-properti/dki-jakarta/114',
                'https://www.rumah.com/agen-properti/dki-jakarta/115',
                'https://www.rumah.com/agen-properti/dki-jakarta/116',
                'https://www.rumah.com/agen-properti/dki-jakarta/117',
                'https://www.rumah.com/agen-properti/dki-jakarta/118',
                'https://www.rumah.com/agen-properti/dki-jakarta/119',
                'https://www.rumah.com/agen-properti/dki-jakarta/120',
                'https://www.rumah.com/agen-properti/dki-jakarta/121',
                'https://www.rumah.com/agen-properti/dki-jakarta/122',
                'https://www.rumah.com/agen-properti/dki-jakarta/123',
                'https://www.rumah.com/agen-properti/dki-jakarta/124',
                'https://www.rumah.com/agen-properti/dki-jakarta/125',
                'https://www.rumah.com/agen-properti/dki-jakarta/126',
                'https://www.rumah.com/agen-properti/dki-jakarta/127',
                'https://www.rumah.com/agen-properti/dki-jakarta/128',
                'https://www.rumah.com/agen-properti/dki-jakarta/129',
                'https://www.rumah.com/agen-properti/dki-jakarta/130',
                'https://www.rumah.com/agen-properti/dki-jakarta/131',
                'https://www.rumah.com/agen-properti/dki-jakarta/132',
                'https://www.rumah.com/agen-properti/dki-jakarta/133',
                'https://www.rumah.com/agen-properti/dki-jakarta/134',
                'https://www.rumah.com/agen-properti/dki-jakarta/135',
                'https://www.rumah.com/agen-properti/dki-jakarta/136',
                'https://www.rumah.com/agen-properti/dki-jakarta/137',
                'https://www.rumah.com/agen-properti/dki-jakarta/138',
                'https://www.rumah.com/agen-properti/dki-jakarta/139',
                'https://www.rumah.com/agen-properti/dki-jakarta/140',
                'https://www.rumah.com/agen-properti/dki-jakarta/141',
                'https://www.rumah.com/agen-properti/dki-jakarta/142',
                'https://www.rumah.com/agen-properti/dki-jakarta/143',
                'https://www.rumah.com/agen-properti/dki-jakarta/144',
                'https://www.rumah.com/agen-properti/dki-jakarta/145',
                'https://www.rumah.com/agen-properti/dki-jakarta/146',
                'https://www.rumah.com/agen-properti/dki-jakarta/147',
                'https://www.rumah.com/agen-properti/dki-jakarta/148',
                'https://www.rumah.com/agen-properti/dki-jakarta/149',
                'https://www.rumah.com/agen-properti/dki-jakarta/150',
                'https://www.rumah.com/agen-properti/dki-jakarta/151',
                'https://www.rumah.com/agen-properti/dki-jakarta/152',
                'https://www.rumah.com/agen-properti/dki-jakarta/153',
                'https://www.rumah.com/agen-properti/dki-jakarta/154',
                'https://www.rumah.com/agen-properti/dki-jakarta/155',
                'https://www.rumah.com/agen-properti/dki-jakarta/156',
                'https://www.rumah.com/agen-properti/dki-jakarta/157',
                'https://www.rumah.com/agen-properti/dki-jakarta/158',
                'https://www.rumah.com/agen-properti/dki-jakarta/159',
                'https://www.rumah.com/agen-properti/dki-jakarta/160',
                'https://www.rumah.com/agen-properti/dki-jakarta/161',
                'https://www.rumah.com/agen-properti/dki-jakarta/162',
                'https://www.rumah.com/agen-properti/dki-jakarta/163',
                'https://www.rumah.com/agen-properti/dki-jakarta/164',
                'https://www.rumah.com/agen-properti/dki-jakarta/165',
                'https://www.rumah.com/agen-properti/dki-jakarta/166',
                'https://www.rumah.com/agen-properti/dki-jakarta/167',
                'https://www.rumah.com/agen-properti/dki-jakarta/168',
                'https://www.rumah.com/agen-properti/dki-jakarta/169',
                'https://www.rumah.com/agen-properti/dki-jakarta/170',
                'https://www.rumah.com/agen-properti/dki-jakarta/171',
                'https://www.rumah.com/agen-properti/dki-jakarta/172',

        ]

        for url in urls:
            yield scrapy.Request(url=get_scrapeops_url(url), callback=self.parse)

    def parse(self, response):

        for href in response.xpath("//div[@class='agent-contact']/a[@class='nav-link agent-contact-button']"):
            yield {
                "href": href.xpath('@href').extract_first(0)
            }



        """items = names()
        name = response.xpath('//*[@id="wrapper-inner"]/div[8]/div/div/div/section/div[3]/div[1]/div[1]/div[3]/a/@href').extract_first()
        items['name'] = name

        yield items"""


"""                "https://www.rumah.com/agen-properti/bali",
                    "https://www.rumah.com/agen-properti/di-yogyakarta",
                    "https://www.rumah.com/agen-properti/nanggroe-aceh-darussalam",
                    "https://www.rumah.com/agen-properti/kep-bangka-belitung",
                    "https://www.rumah.com/agen-properti/bengkulu",
                    "https://www.rumah.com/agen-properti/banten",
                    "https://www.rumah.com/agen-properti/gorontalo",
                    "https://www.rumah.com/agen-properti/jambi",
                    "https://www.rumah.com/agen-properti/jawa-barat",
                    "https://www.rumah.com/agen-properti/jawa-timur",
                    "https://www.rumah.com/agen-properti/jawa-tengah",
                    "https://www.rumah.com/agen-properti/kalimantan-barat",
                    "https://www.rumah.com/agen-properti/kalimantan-timur",
                    "https://www.rumah.com/agen-properti/kep-riau",
                    "https://www.rumah.com/agen-properti/kalimantan-selatan",
                    "https://www.rumah.com/agen-properti/kalimantan-tengah",
                    "https://www.rumah.com/agen-properti/lampung",
                    "https://www.rumah.com/agen-properti/maluku",
                    "https://www.rumah.com/agen-properti/maluku-utara",
                    "https://www.rumah.com/agen-properti/nusa-tenggara-barat",
                    "https://www.rumah.com/agen-properti/nusa-tenggara-timur", 
                    "https://www.rumah.com/agen-properti/papua",
                    "https://www.rumah.com/agen-properti/papua-barat",
                    "https://www.rumah.com/agen-properti/riau",
                    "https://www.rumah.com/agen-properti/sulawesi-utara",
                    "https://www.rumah.com/agen-properti/sumatera-barat",
                    "https://www.rumah.com/agen-properti/sumatera-selatan",
                    "https://www.rumah.com/agen-properti/sulawesi-tengah",
                    "https://www.rumah.com/agen-properti/sumatera-utara"""
